version: "3"
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./custom.conf:/etc/nginx/conf.d/custom.conf
  letsencrypt-nginx-proxy-companion: 
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: letsencrypt-nginx-proxy-companion
    environment:
      - DEFAULT_EMAIL=helpdesk@gbif.no
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  certs:
  vhostd:
  html:
networks:
  default:
    external:
      name: nginx-proxy
